import type { IconType } from "react-icons";
import {
  FaAws,
  FaArrowsRotate,
  FaBolt,
  FaBookOpen,
  FaBrain,
  FaBullseye,
  FaChalkboardUser,
  FaChartLine,
  FaCircleNodes,
  FaCode,
  FaCodeBranch,
  FaCommentDots,
  FaComments,
  FaCompass,
  FaCompress,
  FaCubesStacked,
  FaDatabase,
  FaDiagramProject,
  FaEnvelope,
  FaGaugeHigh,
  FaGithub,
  FaGraduationCap,
  FaHandshake,
  FaHeart,
  FaJava,
  FaKey,
  FaLayerGroup,
  FaLightbulb,
  FaLinkedin,
  FaListCheck,
  FaNetworkWired,
  FaObjectGroup,
  FaPeopleGroup,
  FaReact,
  FaScaleBalanced,
  FaServer,
  FaShieldHalved,
  FaSitemap,
  FaUserCheck,
  FaUsersGear,
  FaVialCircleCheck,
  FaWhatsapp,
} from "react-icons/fa6";
import {
  SiCisco,
  SiCoursera,
  SiCss,
  SiDocker,
  SiFastapi,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGrafana,
  SiHtml5,
  SiJavascript,
  SiLinux,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPrometheus,
  SiPython,
  SiSqlalchemy,
  SiTailwindcss,
  SiTypescript,
  SiVite,
} from "react-icons/si";

/**
 * Data files reference icons by name so they stay serialisable and framework-free.
 * Names are listed explicitly rather than pulled from a namespace import, because a
 * namespace import of react-icons defeats tree-shaking and pulls in every icon.
 */
export const icons = {
  FaAws,
  FaArrowsRotate,
  FaBolt,
  FaBookOpen,
  FaBrain,
  FaBullseye,
  FaChalkboardUser,
  FaChartLine,
  FaCircleNodes,
  FaCode,
  FaCodeBranch,
  FaCommentDots,
  FaComments,
  FaCompass,
  FaCompress,
  FaCubesStacked,
  FaDatabase,
  FaDiagramProject,
  FaEnvelope,
  FaGaugeHigh,
  FaGithub,
  FaGraduationCap,
  FaHandshake,
  FaHeart,
  FaJava,
  FaKey,
  FaLayerGroup,
  FaLightbulb,
  FaLinkedin,
  FaListCheck,
  FaNetworkWired,
  FaObjectGroup,
  FaPeopleGroup,
  FaReact,
  FaScaleBalanced,
  FaServer,
  FaShieldHalved,
  FaSitemap,
  FaUserCheck,
  FaUsersGear,
  FaVialCircleCheck,
  FaWhatsapp,
  SiCisco,
  SiCoursera,
  SiCss,
  SiDocker,
  SiFastapi,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGrafana,
  SiHtml5,
  SiJavascript,
  SiLinux,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPrometheus,
  SiPython,
  SiSqlalchemy,
  SiTailwindcss,
  SiTypescript,
  SiVite,
} satisfies Record<string, IconType>;

/** Restricts data files to icons that actually exist, instead of failing at runtime. */
export type IconName = keyof typeof icons;

export function getIcon(name: IconName): IconType {
  return icons[name];
}
